services:
  - type: web
    name: orni-models-api
    runtime: docker
    repo: https://github.com/anndrrson/orni-models
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ESCROW_WALLET_ADDRESS
        value: H1zX51s8Fba3FYymhSvQ5fTNK5AVwnJJMaDJ59upumAf
      - key: BIND_ADDR
        value: 0.0.0.0:8080
